### ISSUE TITLE
Multiple nodes (with same ID) in mesh address list

### ISSUE THREAD

**Issue by ricmail85** [TMRh20/RF24Mesh#50] opened 2015-12-02 21:09 UTC
Hi,

I'm finding several issues in the last release. 
In my project, each time I boot a node, it starts with the temporary 255 nodeID and then the master reassign a unique nodeID in the range 1-254. 
Now it happens that if I boot (not at the same time) several nodes, the master results a mesh address list in which the 255 nodeid is listed several times... 
Is it due to the fact that now (in several functions, e.g. setAddress()) the nodeID is declared as a char?

Thanks in advance!

**Comment by TMRh20** [comment] 2015-12-02 21:16
That is the expected behaviour with duplicate nodeids.

Sent from my iPod

On 2015-12-02, at 3:10 PM, ricmail85 <notifications@github.com> wrote:

Hi,

I'm finding several issues in the last release.
In my project, each time I boot a node, it starts with the temporary 255
nodeID and then the master reassign a unique nodeID in the range 1-254.
Now it happens that if I boot (not at the same time) several nodes, the
master results a mesh address list in which the 255 nodeid is listed
several times...
Is it due to the fact that now (in several functions, e.g. setAddress())
the nodeID is declared as a char?

Thanks in advance!

—
Reply to this email directly or view it on GitHub
<https://github.com/TMRh20/RF24Mesh/issues/50>.

**Comment by Avamander** [comment] 2015-12-02 21:21
Why are you dynamically assigning NodeIDs?

**Comment by ricmail85** [comment] 2015-12-03 06:16
Ok, thanks for the reply.

I use dynamic nodeids because the number of nodes is not fixed and I want to avoid any user interaction with the single nodes, all the job is done by the master.

In previous releases, if two nodes had the same nodeid there was an unique id listed on the master... Is it right? Why now they are listed several times?

**Comment by ricmail85** [comment] 2015-12-03 19:31
Ok, I've checked and it is related to func setAddress(char nodeID, uint16_t address). If I change it to setAddress(uint8_t nodeID, uint16_t address), there are no duplicate nodeIDs.
Probably the same applies for the setStaticAddress(char nodeID, uint16_t address)... the nodeID parameter should be uint8_t, not char.

is it right?
bye.

**Comment by TMRh20** [comment] 2015-12-05 10:48
Hmm, looking at this function I'm wondering why its using a char. Will have to get it changed soon.

**Comment by Avamander** [comment] 2015-12-15 20:07
Many thanks to @TMRh20 for fixing this issue and @ricmail85 for reporting it.

**Closed** 2015-12-15 20:06 UTC
Labels: bug

**Comment by beuleal** [comment] 2017-03-22 11:14
I have a similar app. I know that this topic is already closed but when i use setAddress(uint8_t nodeID, uint16_t address), function, it should only change the nodeID based in the address, right? I fell that the function is adding the new module into the module's list rather than edit the nodeID.

**Comment by Avamander** [comment] 2017-03-22 16:07
Well, looking at the examples, I'd say one sets the address before the node connects.

**Comment by KevinLod** [comment] 2018-08-21 15:48
Im working at a project with this awesome library,  but i assigned nodes id manually, i want to automat this by using the DHCP function. But the example codes aren't functioning well, would any body direct me to the right way please (im nooooobe)

**Comment by beuleal** [comment] 2018-08-21 15:52
@KevinLod My solution was create a commom ID, like 1234. When master receive any packet from 1234, it looks his node table i created and assign another ID, like 9234, and the old node 1234 restarts itself with the newer ID 9234.
